title: Learning, Perception, and Action - from Metric-Semantic Scene Understanding to High-level Task Execution
description: Title
sitename: perceptionAndAction@ICRA2020
baseurl: 'https://lucacarlone.github.io/2020ws-ICRA-website/'

sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Makefile
theme: jekyll-theme-cayman
