title: Perception, Action, Learning - from Metric-Semantic Scene Understanding to High-level Task Execution
description: Title
sitename: PAL@ICRA2020
baseurl: /PAL-ICRA2020
url: https://mit-spark.github.io

sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Makefile
theme: jekyll-theme-cayman
