title: Learning, Perception, and Action - from Metric-Semantic Scene Understanding to High-level Task Execution
description: Title
sitename: perceptionAndAction@ICRA2020
baseurl: “/2020ws-ICRA-website/”
url: “https://lucacarlone.github.io”

sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Makefile
theme: jekyll-theme-cayman
